### PR TITLE
added Digger Dan

### PR DESCRIPTION
**Pull request by Bedazzle**

### CODE REVIEW

**Comment by skoolkid** [comment]
Hi @Bedazzle - thanks for this! A couple of points:

- The naming convention uses hyphens instead of underscores: `digger-dan.z80`
- Even if `tap2sna.py` figures out the start address automatically (as in this case), it should be explicitly included in the `t2s` file to indicate that is has been determined (one way or another): `--start 24576`

Also, feel free to add a comment at the top of the `t2s` file stating that you're the contributor (if you wish). Any line that starts with `;` or `#` is interpreted as a comment; for example:

    ; Contributed by Bedazzle

**Comment by Bedazzle** [comment]
Sure, I fix these!

**Comment by skoolkid** [comment]
Nearly there. Can you:

- Change `digger_dan.z80` to `digger-dan.z80`.
- Rename `earth-shacker.t2s` to `earth-shaker.t2s` and change `earth-shacker.z80` to `earth-shaker.z80` accordingly.

**Comment by skoolkid** [comment]
Looks good. Do you want to add any more files before merging?

**Comment by Bedazzle** [comment]
Not today, but later yes.

**Pull request merged**
