### PR TITLE
Add more games

### PR DESCRIPTION
**Pull request by Bedazzle**
Motojet
Music logic
Nihilist
Notorik
Pacmans revenge
Peloponnesian war
Perestrojka
Pipe line (Dominic Morris)
Power magic
Reversor
Runaway robot

Not sure which one must be present (or both):
Poklad 2 (Fuxoft)
Poklad 2 (Proxima software)

### CODE REVIEW

**Comment by skoolkid** [comment]
Hi @Bedazzle. It looks like `notorik.t2s` is the only new title here - the others are already in the repo. Shall I add that one manually, or do you want to adjust this PR to remove the conflicts?

**Comment by Bedazzle** [comment]
Manual is ok. Seems, I need to send new titles faster than you are doing these. :)

**Comment by skoolkid** [comment]
How did you get the start address of 32934 ($80A6) for Notorik? To me it looks like 32903 ($8087) is a more natural start address, because it's where the final descrambling loop returns to:

    ...
    $8120 LD A,C
    $8121 ADD A,$3B
    $8123 LD C,A
    $8124 XOR (HL)
    $8125 LD (HL),A
    $8126 INC HL
    $8127 DEC DE
    $8128 LD A,D
    $8129 OR E
    $812A JR NZ,$8120
    $812C RET
    $8087 LD SP,$7080
    $808A LD HL,$82BD
    $808D LD DE,$5C00
    $8090 LD BC,$00D8
    $8093 LDIR
    ...

**Comment by Bedazzle** [comment]
I think, as address on stack. Maybe, incorrectly converted hex/dec, because did it manually.

**Comment by skoolkid** [comment]
`notorik.t2s` added in f3b12e2c7ec8ee162f4a3b015cd6df49494be2d6.

**Pull request closed without merging**
